dataset: cifar10
model: simple_cnn
feat_dim: 3
img_size: 32
learning_rate: 0.003
weight_decay: 0.00005
classes: 10
epochs: 30
train_batch_size: 2048
test_batch_size: 2048
val_freq: 1
uncert_epochs: 30
uncert_batch_size: 512
resume:
test_path: cifar10_simple_cnn_model_best.pth
patience: 7
