dataset: mnist # [mnist, cifar10, food101]
model: custom
feat_dim: 1
img_size: 28
learning_rate: 0.003
weight_decay: 0.00005
classes: 10
epochs: 10
train_batch_size: 2048
test_batch_size: 4096
val_freq: 1
uncert_epochs: 30
uncert_batch_size: 512
resume:
test_path: mnist_custom_model_best.pth
