dataset: dtd # [mnist, cifar10, food101]
model: resnet-18
feat_dim: 3
img_size: 224
learning_rate: 0.003
weight_decay: 0.00005
classes: 47
epochs: 30
train_batch_size: 128
test_batch_size: 512
val_freq: 1
uncert_epochs: 30
uncert_batch_size: 512
resume:
test_path: dtd_resnet-18_model_best.pth
