dataset: food101
model: larger_cnn
feat_dim: 3
img_size: 224
learning_rate: 0.003
weight_decay: 0.00005
classes: 101
epochs: 30
batch_size: 128
val_freq: 1
uncert_epochs: 10
uncert_batchsize: 64
resume:
