dataset: food101
model: mlp
feat_dim: 3
img_size: 224
learning_rate: 0.003
weight_decay: 0.00005
classes: 101
epochs: 10
batch_size: 1024
val_freq: 1
uncert_epochs: 10
uncert_batchsize: 512
resume:
test_path:
