dataset: food101
model: mlp
feat_dim: 3
img_size: 224
learning_rate: 0.003
weight_decay: 0.00005
classes: 101
epochs: 30
train_batch_size: 1024
test_batch_size: 2048
val_freq: 1
uncert_epochs: 30
uncert_batch_size: 512
resume:
test_path: food101_mlp_model_best.pth
