dataset: mnist
model: mlp
feat_dim: 1
img_size: 28
learning_rate: 0.003
weight_decay: 0.00005
classes: 10
epochs: 10
train_batch_size: 16384
test_batch_size: 8192
val_freq: 1
uncert_epochs: 30
uncert_batch_size: 8192
resume:
test_path: mnist_mlp_model_best.pth
