dataset: mnist
model: mlp
feat_dim: 1
img_size: 28
learning_rate: 0.003
weight_decay: 0.00005
classes: 10
epochs: 10
batch_size: 8192
val_freq: 1
uncert_epochs: 10
uncert_batchsize: 4096
resume:
test_path:
